-- Migration: Create RPC to get order items details
-- Date: 2026-01-29 10:45:00

DROP FUNCTION IF EXISTS get_order_items_details(TEXT);

CREATE OR REPLACE FUNCTION get_order_items_details(
  p_ped_numpedido TEXT
)
RETURNS TABLE (
  "MATRIZ" INT,
  "FILIAL" INT,
  "PED_NUMPEDIDO" TEXT,
  "ITEM_CODIGO" TEXT,
  "DESCRICAO" TEXT,
  "QTDE_PEDIDA" NUMERIC,
  "QTDE_ENTREGUE" NUMERIC,
  "QTDE_SALDO" NUMERIC,
  "VALOR_UNITARIO" NUMERIC,
  "VALOR_TOTAL" NUMERIC
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p."MATRIZ",
    p."FILIAL",
    p."PED_NUMPEDIDO"::TEXT,
    p."ITEM_CODIGO"::TEXT,
    i."DESCRICAO"::TEXT,
    COALESCE(p."QTDE_PEDIDA", 0) as "QTDE_PEDIDA",
    COALESCE(p."QTDE_ENTREGUE", 0) as "QTDE_ENTREGUE",
    COALESCE(p."QTDE_SALDO", 0) as "QTDE_SALDO",
    COALESCE(p."VALOR_UNITARIO", 0) as "VALOR_UNITARIO",
    (COALESCE(p."QTDE_PEDIDA", 0) * COALESCE(p."VALOR_UNITARIO", 0)) as "VALOR_TOTAL"
  FROM "BLUEBAY_PEDIDO" p
  LEFT JOIN "BLUEBAY_ITEM" i ON p."ITEM_CODIGO" = i."ITEM_CODIGO"
  WHERE p."PED_NUMPEDIDO" = p_ped_numpedido
  ORDER BY p."ITEM_CODIGO";
END;
$$ LANGUAGE plpgsql;
